### ISSUE TITLE
Deleting Canvas which is still live

### ISSUE THREAD

**Issue by remykonings** [streamr-dev/core-frontend#417] opened 2019-05-11 11:31 UTC
I turns out that you can try to delete a canvast from the canvas overview that nothing happens because the canvas is still live. You can only delete the canvas if it has stopped.

What needs to happen i think, is that or the delete button in the canvas page is grayed out because it is still live and therefor it can not happen or when you try to delete it that it just goes through with it and it stops the canvas all together.

**App version**
Open editor sidebar to see the app version [e.g. Streamr App v2.0.5-574-ga787e4e]

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Brave
 - Version 0.63.55 Chromium: 74.0.3729.131 (Official Build) (64-bit)

**Comment by fonty1** [comment] 2019-05-13 08:34
Tested and I can reproduce this. Thanks for the heads up- I will assign this bugfix to me.

I believe the intended behaviour is to disable the delete button for running canvases - @mattatgit  can you confirm this?

**Comment by mattatgit** [comment] 2019-05-13 09:07
@fonty1 Well there are various discussions on how to best solve this, which is part of a bigger issue. eg via multi-select etc. But disabling the on tile delete is a reasonable step for the time being.

**Closed** 2022-07-06 07:46 UTC
